//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Components.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Components.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;div id=&quot;disqus_thread&quot;&gt;&lt;/div&gt;
        ///&lt;script&gt;
        ///var disqus_config = function () {
        ///this.page.url = &apos;www.example.com&apos;;
        ///this.page.identifier = &apos;www.example.com&apos;;
        ///};
        ///(function() {
        ///var d = document, s = d.createElement(&apos;script&apos;);
        ///s.src = &apos;https://test.disqus.com/embed.js&apos;;
        ///s.setAttribute(&apos;data-timestamp&apos;, +new Date());
        ///(d.head || d.body).appendChild(s);
        ///})();
        ///&lt;/script&gt;
        ///&lt;noscript&gt;Please enable JavaScript to view the &lt;a href=&quot;https://disqus.com/?ref_noscript&quot;&gt;comments powered by Disqus.&lt;/a&gt;&lt;/noscript&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string disqus1 {
            get {
                return ResourceManager.GetString("disqus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;div id=&quot;disqus_thread&quot;&gt;&lt;/div&gt;
        ///&lt;script&gt;
        ///var disqus_config = function () {
        ///this.page.url = &apos;www.example.com&apos;;
        ///this.page.identifier = &apos;www.example.com&apos;;
        ///};
        ///(function() {
        ///var d = document, s = d.createElement(&apos;script&apos;);
        ///s.src = &apos;https://test.disqus.com/embed.js&apos;;
        ///s.setAttribute(&apos;data-timestamp&apos;, +new Date());
        ///(d.head || d.body).appendChild(s);
        ///})();
        ///&lt;/script&gt;
        ///&lt;noscript&gt;Please enable JavaScript to view the &lt;a href=&quot;https://disqus.com/?ref_noscript&quot;&gt;comments powered by Disqus.&lt;/a&gt;&lt;/noscript&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string disqus2 {
            get {
                return ResourceManager.GetString("disqus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;channel&gt;
        ///&lt;title&gt;&lt;/title&gt;
        ///&lt;description&gt;&lt;/description&gt;
        ///&lt;link&gt;www.example.com&lt;/link&gt;
        ///&lt;lastBuildDate&gt;-&lt;/lastBuildDate&gt;
        ///&lt;atom:link href=&quot;www.example.com/feed.xml&quot; rel=&quot;self&quot; type=&quot;application/rss+xml&quot; /&gt;
        ///&lt;item&gt;
        ///&lt;title&gt;p1&lt;/title&gt;
        ///&lt;description&gt;desc1&lt;/description&gt;
        ///&lt;link&gt;www.example.com/Page1/&lt;/link&gt;
        ///&lt;guid isPermaLink=&quot;true&quot;&gt;www.example.com/Page1/&lt;/guid&gt;
        ///&lt;/item&gt;
        ///&lt;item&gt;
        ///&lt;title&gt;sp1&lt;/title&gt;
        ///&lt;description&gt;&lt;/description&gt;
        ///&lt;link&gt;www.example.com/Page1/SubPage1/&lt;/link&gt;
        ///&lt;guid isPermaLink=&quot;true&quot;&gt;www.example.com [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string feed1 {
            get {
                return ResourceManager.GetString("feed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;channel&gt;
        ///&lt;title&gt;&lt;/title&gt;
        ///&lt;description&gt;&lt;/description&gt;
        ///&lt;link&gt;www.example.com&lt;/link&gt;
        ///&lt;image&gt;
        ///&lt;url&gt;www.example.com/img1.png&lt;/url&gt;
        ///&lt;title&gt;&lt;/title&gt;
        ///&lt;link&gt;www.example.com&lt;/link&gt;
        ///&lt;/image&gt;
        ///&lt;lastBuildDate&gt;-&lt;/lastBuildDate&gt;
        ///&lt;atom:link href=&quot;www.example.com/feed.xml&quot; rel=&quot;self&quot; type=&quot;application/rss+xml&quot; /&gt;
        ///&lt;/channel&gt;.
        /// </summary>
        internal static string feed2 {
            get {
                return ResourceManager.GetString("feed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;channel&gt;
        ///&lt;title&gt;&lt;/title&gt;
        ///&lt;description&gt;&lt;/description&gt;
        ///&lt;link&gt;www.example.com&lt;/link&gt;
        ///&lt;lastBuildDate&gt;-&lt;/lastBuildDate&gt;
        ///&lt;atom:link href=&quot;www.example.com/feed.xml&quot; rel=&quot;self&quot; type=&quot;application/rss+xml&quot; /&gt;
        ///&lt;item&gt;
        ///&lt;title&gt;p1&lt;/title&gt;
        ///&lt;description&gt;&lt;/description&gt;
        ///&lt;link&gt;www.example.com/Page1/&lt;/link&gt;
        ///&lt;guid isPermaLink=&quot;true&quot;&gt;www.example.com/Page1/&lt;/guid&gt;
        ///&lt;category&gt;cat1&lt;/category&gt;
        ///&lt;category&gt;cat2&lt;/category&gt;
        ///&lt;/item&gt;
        ///&lt;/channel&gt;.
        /// </summary>
        internal static string feed3 {
            get {
                return ResourceManager.GetString("feed3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;channel&gt;
        ///&lt;title&gt;&lt;/title&gt;
        ///&lt;description&gt;&lt;/description&gt;
        ///&lt;link&gt;www.example.com&lt;/link&gt;
        ///&lt;lastBuildDate&gt;-&lt;/lastBuildDate&gt;
        ///&lt;atom:link href=&quot;www.example.com/feed.xml&quot; rel=&quot;self&quot; type=&quot;application/rss+xml&quot; /&gt;
        ///&lt;/channel&gt;.
        /// </summary>
        internal static string feed4 {
            get {
                return ResourceManager.GetString("feed4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script async src=&quot;https://www.googletagmanager.com/gtag/js?id=ABC&quot;&gt;&lt;/script&gt;
        ///&lt;script&gt;
        ///window.dataLayer = window.dataLayer || [];
        ///function gtag() { dataLayer.push(arguments); }
        ///gtag(&apos;js&apos;, new Date());
        ///gtag(&apos;config&apos;, &apos;ABC&apos;);
        ///&lt;/script&gt;.
        /// </summary>
        internal static string google_analytics1 {
            get {
                return ResourceManager.GetString("google-analytics1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;ul class=&quot;menu sub-menu-item-container&quot; id=&quot;top-menu&quot;&gt;
        ///&lt;a class=&quot;menu-icon&quot; onclick=&quot;OpenMenu(this)&quot;&gt;
        ///&lt;div class=&quot;bar1&quot;&gt;&lt;/div&gt;
        ///&lt;div class=&quot;bar2&quot;&gt;&lt;/div&gt;
        ///&lt;div class=&quot;bar3&quot;&gt;&lt;/div&gt;
        ///&lt;/a&gt;
        ///&lt;li class=&quot;menu-item not-active&quot;&gt;
        ///&lt;a&gt;Page1▾&lt;/a&gt;
        ///&lt;ul class=&quot;sub-menu-item-container&quot;&gt;
        ///&lt;li class=&quot;menu-item not-active&quot;&gt;
        ///&lt;a href=&quot;/p2/&quot;&gt;p2&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;li class=&quot;menu-item not-active&quot;&gt;
        ///&lt;a&gt;SubPage2&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;/li&gt;
        ///&lt;li class=&quot;menu-item not-active&quot;&gt;
        ///&lt;a&gt;Page2&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string nav1 {
            get {
                return ResourceManager.GetString("nav1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;ul class=&quot;menu sub-menu-item-container&quot; id=&quot;top-menu&quot;&gt;
        ///&lt;a class=&quot;menu-icon&quot; onclick=&quot;OpenMenu(this)&quot;&gt;
        ///&lt;div class=&quot;bar1&quot;&gt;&lt;/div&gt;
        ///&lt;div class=&quot;bar2&quot;&gt;&lt;/div&gt;
        ///&lt;div class=&quot;bar3&quot;&gt;&lt;/div&gt;
        ///&lt;/a&gt;
        ///&lt;li class=&quot;menu-item not-active&quot;&gt;
        ///&lt;a href=&quot;/Page1/&quot;&gt;p1▾&lt;/a&gt;
        ///&lt;ul class=&quot;sub-menu-item-container&quot;&gt;
        ///&lt;li class=&quot;menu-item not-active&quot;&gt;
        ///&lt;a href=&quot;/Page1/SubPage1/&quot;&gt;sp1&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;li class=&quot;menu-item not-active&quot;&gt;
        ///&lt;a href=&quot;/Page1/SubPage2/&quot;&gt;sp2&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;/li&gt;
        ///&lt;li class=&quot;menu-item not-active&quot;&gt;
        ///&lt;a href=&quot;/P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nav2 {
            get {
                return ResourceManager.GetString("nav2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;ul class=&quot;menu sub-menu-item-container&quot; id=&quot;top-menu&quot;&gt;
        ///&lt;a class=&quot;menu-icon&quot; onclick=&quot;OpenMenu(this)&quot;&gt;
        ///&lt;div class=&quot;bar1&quot;&gt;&lt;/div&gt;
        ///&lt;div class=&quot;bar2&quot;&gt;&lt;/div&gt;
        ///&lt;div class=&quot;bar3&quot;&gt;&lt;/div&gt;
        ///&lt;/a&gt;
        ///&lt;li class=&quot;menu-item active&quot;&gt;
        ///&lt;a href=&quot;/&quot;&gt;Home&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;li class=&quot;menu-item not-active&quot;&gt;
        ///&lt;a href=&quot;/Page1/&quot;&gt;p1&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string nav3 {
            get {
                return ResourceManager.GetString("nav3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;ul class=&quot;menu sub-menu-item-container&quot; id=&quot;top-menu&quot;&gt;
        ///&lt;a class=&quot;menu-icon&quot; onclick=&quot;OpenMenu(this)&quot;&gt;
        ///&lt;div class=&quot;bar1&quot;&gt;&lt;/div&gt;
        ///&lt;div class=&quot;bar2&quot;&gt;&lt;/div&gt;
        ///&lt;div class=&quot;bar3&quot;&gt;&lt;/div&gt;
        ///&lt;/a&gt;
        ///&lt;li class=&quot;menu-item not-active&quot;&gt;
        ///&lt;a href=&quot;/Page1/&quot;&gt;x1&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string nav4 {
            get {
                return ResourceManager.GetString("nav4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;ul class=&quot;menu sub-menu-item-container&quot; id=&quot;top-menu&quot;&gt;
        ///&lt;a class=&quot;menu-icon&quot; onclick=&quot;OpenMenu(this)&quot;&gt;
        ///&lt;div class=&quot;bar1&quot;&gt;&lt;/div&gt;
        ///&lt;div class=&quot;bar2&quot;&gt;&lt;/div&gt;
        ///&lt;div class=&quot;bar3&quot;&gt;&lt;/div&gt;
        ///&lt;/a&gt;
        ///&lt;li class=&quot;menu-item not-active&quot;&gt;
        ///&lt;a href=&quot;/Page1/SubPage1/&quot;&gt;sp1&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;li class=&quot;menu-item not-active&quot;&gt;
        ///&lt;a href=&quot;/Page1/SubPage2/&quot;&gt;sp2&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string nav5 {
            get {
                return ResourceManager.GetString("nav5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;ul class=&quot;menu sub-menu-item-container&quot; id=&quot;top-menu&quot;&gt;
        ///&lt;a class=&quot;menu-icon&quot; onclick=&quot;OpenMenu(this)&quot;&gt;
        ///&lt;div class=&quot;bar1&quot;&gt;&lt;/div&gt;
        ///&lt;div class=&quot;bar2&quot;&gt;&lt;/div&gt;
        ///&lt;div class=&quot;bar3&quot;&gt;&lt;/div&gt;
        ///&lt;/a&gt;
        ///&lt;li class=&quot;menu-item active&quot;&gt;
        ///&lt;a href=&quot;/&quot;&gt;Home&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;li class=&quot;menu-item not-active&quot;&gt;
        ///&lt;a href=&quot;/Page1/&quot;&gt;p1▾&lt;/a&gt;
        ///&lt;ul class=&quot;sub-menu-item-container&quot;&gt;
        ///&lt;li class=&quot;menu-item not-active&quot;&gt;
        ///&lt;a href=&quot;/Page1/SubPage2/&quot;&gt;sp2&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;/li&gt;
        ///&lt;li class=&quot;menu-item not-active&quot;&gt;
        ///&lt;a href=&quot;/Page2/&quot;&gt;p2&lt;/a&gt;
        ///&lt;/l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nav6 {
            get {
                return ResourceManager.GetString("nav6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;title&gt;p1&lt;/title&gt;
        ///&lt;meta name=&quot;generator&quot; content=&quot;Docify&quot; /&gt;
        ///&lt;meta name=&quot;description&quot; content=&quot;d1&quot; /&gt;
        ///&lt;link rel=&quot;canonical&quot; href=&quot;www.example.com&quot; /&gt;
        ///&lt;meta property=&quot;og:title&quot; content=&quot;p1&quot; /&gt;
        ///&lt;meta property=&quot;og:locale&quot; /&gt;
        ///&lt;meta property=&quot;og:description&quot; content=&quot;d1&quot; /&gt;
        ///&lt;meta property=&quot;og:url&quot; content=&quot;www.example.com&quot; /&gt;
        ///&lt;meta property=&quot;og:site_name&quot; content=&quot;t1&quot; /&gt;
        ///&lt;meta property=&quot;og:image&quot; /&gt;
        ///&lt;meta name=&quot;twitter:card&quot; content=&quot;d1&quot; /&gt;
        ///&lt;meta name=&quot;twitter:site&quot; content=&quot;www.example.com&quot; /&gt;
        ///&lt;meta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string seo1 {
            get {
                return ResourceManager.GetString("seo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;title&gt;p1&lt;/title&gt;
        ///&lt;meta name=&quot;generator&quot; content=&quot;Docify&quot; /&gt;
        ///&lt;meta name=&quot;description&quot; content=&quot;d1&quot; /&gt;
        ///&lt;link rel=&quot;canonical&quot; href=&quot;www.example.com&quot; /&gt;
        ///&lt;meta property=&quot;og:title&quot; content=&quot;p1&quot; /&gt;
        ///&lt;meta property=&quot;og:locale&quot; /&gt;
        ///&lt;meta property=&quot;og:description&quot; content=&quot;d1&quot; /&gt;
        ///&lt;meta property=&quot;og:url&quot; content=&quot;www.example.com&quot; /&gt;
        ///&lt;meta property=&quot;og:site_name&quot; content=&quot;t1&quot; /&gt;
        ///&lt;meta property=&quot;og:image&quot; /&gt;.
        /// </summary>
        internal static string seo2 {
            get {
                return ResourceManager.GetString("seo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;title&gt;p1&lt;/title&gt;
        ///&lt;meta name=&quot;generator&quot; content=&quot;Docify&quot; /&gt;
        ///&lt;meta name=&quot;description&quot; content=&quot;d1&quot; /&gt;
        ///&lt;link rel=&quot;canonical&quot; href=&quot;www.example.com&quot; /&gt;
        ///&lt;meta name=&quot;twitter:card&quot; content=&quot;d1&quot; /&gt;
        ///&lt;meta name=&quot;twitter:site&quot; content=&quot;www.example.com&quot; /&gt;
        ///&lt;meta name=&quot;twitter:title&quot; content=&quot;p1&quot; /&gt;
        ///&lt;meta name=&quot;twitter:description&quot; content=&quot;d1&quot; /&gt;
        ///&lt;meta name=&quot;twitter:image&quot; /&gt;.
        /// </summary>
        internal static string seo3 {
            get {
                return ResourceManager.GetString("seo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;title&gt;p1&lt;/title&gt;
        ///&lt;meta name=&quot;generator&quot; content=&quot;Docify&quot; /&gt;
        ///&lt;meta name=&quot;description&quot; content=&quot;d1&quot; /&gt;
        ///&lt;link rel=&quot;canonical&quot; href=&quot;www.example.com&quot; /&gt;
        ///&lt;script type=&quot;application/ld+json&quot;&gt;
        ///{&quot;url&quot;:&quot;www.example.com&quot;,&quot;description&quot;:&quot;d1&quot;,&quot;headline&quot;:&quot;d1&quot;,&quot;image&quot;:null,&quot;@type&quot;:&quot;WebPage&quot;,&quot;@context&quot;:&quot;http://schema.org&quot;}
        ///&lt;/script&gt;.
        /// </summary>
        internal static string seo4 {
            get {
                return ResourceManager.GetString("seo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;title&gt;p1&lt;/title&gt;
        ///&lt;meta name=&quot;generator&quot; content=&quot;Docify&quot; /&gt;
        ///&lt;meta name=&quot;description&quot; content=&quot;d1&quot; /&gt;
        ///&lt;link rel=&quot;canonical&quot; href=&quot;www.example.com&quot; /&gt;
        ///    &lt;meta property=&quot;og:title&quot; content=&quot;p1&quot; /&gt;
        ///    &lt;meta property=&quot;og:locale&quot; /&gt;
        ///    &lt;meta property=&quot;og:description&quot; content=&quot;d1&quot; /&gt;
        ///    &lt;meta property=&quot;og:url&quot; content=&quot;www.example.com&quot; /&gt;
        ///    &lt;meta property=&quot;og:site_name&quot; /&gt;
        ///    &lt;meta property=&quot;og:image&quot; content=&quot;www.example.com/img1.png&quot; /&gt;
        ///    &lt;meta name=&quot;twitter:card&quot; content=&quot;d1&quot; /&gt;
        ///    &lt;met [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string seo5 {
            get {
                return ResourceManager.GetString("seo5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;title&gt;p1&lt;/title&gt;
        ///&lt;meta name=&quot;generator&quot; content=&quot;Docify&quot; /&gt;
        ///&lt;meta name=&quot;description&quot; /&gt;
        ///&lt;link rel=&quot;canonical&quot; href=&quot;www.example.com/Page1/&quot; /&gt;
        ///    &lt;meta property=&quot;og:title&quot; content=&quot;p1&quot; /&gt;
        ///    &lt;meta property=&quot;og:locale&quot; /&gt;
        ///    &lt;meta property=&quot;og:description&quot; /&gt;
        ///    &lt;meta property=&quot;og:url&quot; content=&quot;www.example.com/Page1/&quot; /&gt;
        ///    &lt;meta property=&quot;og:site_name&quot; /&gt;
        ///    &lt;meta property=&quot;og:image&quot; content=&quot;www.example.com/Page1/img2.png&quot; /&gt;
        ///    &lt;meta name=&quot;twitter:card&quot; /&gt;
        ///    &lt;meta name=&quot;twitter:sit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string seo6 {
            get {
                return ResourceManager.GetString("seo6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;urlset xmlns=&quot;http://www.sitemaps.org/schemas/sitemap/0.9&quot;&gt;
        ///&lt;url&gt;
        ///&lt;loc&gt;www.example.com&lt;/loc&gt;
        ///&lt;/url&gt;
        ///&lt;url&gt;
        ///&lt;loc&gt;www.example.com/Page1/&lt;/loc&gt;
        ///&lt;/url&gt;
        ///&lt;url&gt;
        ///&lt;loc&gt;www.example.com/Page2/&lt;/loc&gt;
        ///&lt;/url&gt;
        ///&lt;/urlset&gt;.
        /// </summary>
        internal static string sitemap1 {
            get {
                return ResourceManager.GetString("sitemap1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;div class=&quot;social-share-list&quot;&gt;
        ///&lt;i&gt;Share&lt;/i&gt;
        ///&lt;a href=&quot;https://www.linkedin.com/shareArticle?mini=true&amp;url=www.example.com&quot; onclick=&quot;window.open(this.href, &apos;pop-up&apos;, &apos;left=20,top=20,width=900,height=500,toolbar=1,resizable=0&apos;); return false;&quot; title=&quot;Share on LinkedIn&quot;&gt;
        ///&lt;svg alt=&quot;Share on LinkedIn&quot; class=&quot;social-share-link&quot; fill=&quot;#0077B5&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;
        ///&lt;use xlink:href=&quot;/assets/images/social-share.svg#linkedin&quot; /&gt;
        ///&lt;/svg&gt;
        ///&lt;/a&gt;
        ///&lt;a href=&quot;https://www.facebook.com/sharer/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string social_share1 {
            get {
                return ResourceManager.GetString("social-share1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;div class=&quot;social-share-list&quot;&gt;
        ///&lt;i&gt;Share&lt;/i&gt;
        ///&lt;a href=&quot;https://www.linkedin.com/shareArticle?mini=true&amp;url=www.example.com&quot; onclick=&quot;window.open(this.href, &apos;pop-up&apos;, &apos;left=20,top=20,width=900,height=500,toolbar=1,resizable=0&apos;); return false;&quot; title=&quot;Share on LinkedIn&quot;&gt;
        ///&lt;svg alt=&quot;Share on LinkedIn&quot; class=&quot;social-share-link&quot; fill=&quot;#0077B5&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;
        ///&lt;use xlink:href=&quot;/assets/images/social-share.svg#linkedin&quot; /&gt;
        ///&lt;/svg&gt;
        ///&lt;/a&gt;
        ///&lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string social_share2 {
            get {
                return ResourceManager.GetString("social-share2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;div class=&quot;social-share-list&quot;&gt;
        ///&lt;i&gt;Share&lt;/i&gt;
        ///&lt;a href=&quot;https://www.facebook.com/sharer/sharer.php?u=www.example.com&quot; onclick=&quot;window.open(this.href, &apos;pop-up&apos;, &apos;left=20,top=20,width=900,height=500,toolbar=1,resizable=0&apos;); return false;&quot; title=&quot;Share on Facebook&quot; target=&quot;_blank&quot;&gt;
        ///&lt;svg alt=&quot;Share on Facebook&quot; class=&quot;social-share-link&quot; fill=&quot;#1877F2&quot;&gt;
        ///&lt;use xlink:href=&quot;/assets/images/social-share.svg#facebook&quot; /&gt;
        ///&lt;/svg&gt;
        ///&lt;/a&gt;
        ///&lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string social_share3 {
            get {
                return ResourceManager.GetString("social-share3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;div class=&quot;social-share-list&quot;&gt;
        ///&lt;i&gt;Share&lt;/i&gt;
        ///&lt;a href=&quot;https://www.pinterest.com/pin/create/button/?url=www.example.com&quot; onclick=&quot;window.open(this.href, &apos;pop-up&apos;, &apos;left=20,top=20,width=900,height=500,toolbar=1,resizable=0&apos;); return false;&quot; title=&quot;Share on Pinterest&quot; target=&quot;_blank&quot;&gt;
        ///&lt;svg alt=&quot;Share on Pinterest&quot; class=&quot;social-share-link&quot; fill=&quot;#BD081C&quot;&gt;
        ///&lt;use xlink:href=&quot;/assets/images/social-share.svg#pinterest&quot; /&gt;
        ///&lt;/svg&gt;
        ///&lt;/a&gt;
        ///&lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string social_share4 {
            get {
                return ResourceManager.GetString("social-share4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;div class=&quot;social-share-list&quot;&gt;
        ///&lt;i&gt;Share&lt;/i&gt;
        ///&lt;a href=&quot;http://www.reddit.com/submit?url=www.example.com&quot; onclick=&quot;window.open(this.href, &apos;pop-up&apos;, &apos;left=20,top=20,width=900,height=500,toolbar=1,resizable=0&apos;); return false;&quot; title=&quot;Share on Reddit&quot; target=&quot;_blank&quot;&gt;
        ///&lt;svg alt=&quot;Share on Reddit&quot; class=&quot;social-share-link&quot; fill=&quot;#FF4500&quot;&gt;
        ///&lt;use xlink:href=&quot;/assets/images/social-share.svg#reddit&quot; /&gt;
        ///&lt;/svg&gt;
        ///&lt;/a&gt;
        ///&lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string social_share5 {
            get {
                return ResourceManager.GetString("social-share5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;div class=&quot;social-share-list&quot;&gt;
        ///&lt;i&gt;Share&lt;/i&gt;
        ///&lt;a href=&quot;https://www.linkedin.com/shareArticle?mini=true&amp;url=www.example.com&quot; onclick=&quot;window.open(this.href, &apos;pop-up&apos;, &apos;left=20,top=20,width=900,height=500,toolbar=1,resizable=0&apos;); return false;&quot; title=&quot;Share on LinkedIn&quot;&gt;
        ///&lt;svg alt=&quot;Share on LinkedIn&quot; class=&quot;social-share-link&quot; fill=&quot;green&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;
        ///&lt;use xlink:href=&quot;/assets/images/social-share.svg#linkedin&quot; /&gt;
        ///&lt;/svg&gt;
        ///&lt;/a&gt;
        ///&lt;a href=&quot;https://www.facebook.com/sharer/sh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string social_share6 {
            get {
                return ResourceManager.GetString("social-share6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;div id=&quot;toc&quot;&gt;
        ///&lt;a href=&quot;/&quot; class=&quot;toc-entry  active&quot;&gt;Welcome&lt;/a&gt;
        ///&lt;ul style=&quot;margin: 0px&quot; class=&quot;toc-container collapse in&quot;&gt;
        ///&lt;li&gt;
        ///&lt;div class=&quot;tree-toc-node pointer&quot; onclick=&quot;javascript:toggle(n1Span, n1);&quot;&gt;
        ///&lt;span class=&quot;expbutton&quot; id=&quot;n1Span&quot;&gt;&amp;#9656;&lt;/span&gt;
        ///&lt;span class=&quot;section&quot;&gt;&lt;/span&gt;
        ///&lt;a href=&quot;&quot; class=&quot;toc-entry&quot;&gt;Page1&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;ul id=&quot;n1&quot; class=&quot;toc-container collapse &quot;&gt;
        ///&lt;li&gt;
        ///&lt;div class=&quot;tree-toc-node pointer&quot; &gt;
        ///&lt;span class=&quot;article&quot;&gt;&lt;/span&gt;
        ///&lt;a href=&quot;/p2/&quot; class=&quot;toc-entry&quot;&gt;p2&lt;/a&gt;
        ///&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string toc1 {
            get {
                return ResourceManager.GetString("toc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;div id=&quot;toc&quot;&gt;
        ///&lt;ul style=&quot;margin: 0px&quot; class=&quot;toc-container collapse in&quot;&gt;
        ///&lt;li&gt;
        ///&lt;div class=&quot;tree-toc-node pointer&quot; onclick=&quot;javascript:toggle(n1Span, n1);&quot;&gt;
        ///&lt;span class=&quot;expbutton&quot; id=&quot;n1Span&quot;&gt;&amp;#9656;&lt;/span&gt;
        ///&lt;span class=&quot;section&quot;&gt;&lt;/span&gt;
        ///&lt;a href=&quot;/Page1/&quot; class=&quot;toc-entry&quot;&gt;p1&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;ul id=&quot;n1&quot; class=&quot;toc-container collapse &quot;&gt;
        ///&lt;li&gt;
        ///&lt;div class=&quot;tree-toc-node pointer&quot; &gt;
        ///&lt;span class=&quot;article&quot;&gt;&lt;/span&gt;
        ///&lt;a href=&quot;/Page1/SubPage1/&quot; class=&quot;toc-entry&quot;&gt;sp1&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;li&gt;
        ///&lt;div class=&quot;tree-toc-no [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string toc2 {
            get {
                return ResourceManager.GetString("toc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;div id=&quot;toc&quot;&gt;
        ///&lt;a href=&quot;/&quot; class=&quot;toc-entry  active&quot;&gt;Welcome&lt;/a&gt;
        ///&lt;ul style=&quot;margin: 0px&quot; class=&quot;toc-container collapse in&quot;&gt;
        ///&lt;li&gt;
        ///&lt;div class=&quot;tree-toc-node pointer&quot; &gt;
        ///&lt;span class=&quot;article&quot;&gt;&lt;/span&gt;
        ///&lt;a href=&quot;/Page1/&quot; class=&quot;toc-entry&quot;&gt;p1&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string toc3 {
            get {
                return ResourceManager.GetString("toc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;div id=&quot;toc&quot;&gt;
        ///&lt;ul style=&quot;margin: 0px&quot; class=&quot;toc-container collapse in&quot;&gt;
        ///&lt;li&gt;
        ///&lt;div class=&quot;tree-toc-node pointer&quot; &gt;
        ///&lt;span class=&quot;article&quot;&gt;&lt;/span&gt;
        ///&lt;a href=&quot;/Page1/&quot; class=&quot;toc-entry&quot;&gt;x1&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string toc4 {
            get {
                return ResourceManager.GetString("toc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;div id=&quot;toc&quot;&gt;
        ///&lt;ul style=&quot;margin: 0px&quot; class=&quot;toc-container collapse in&quot;&gt;
        ///&lt;li&gt;
        ///&lt;div class=&quot;tree-toc-node pointer&quot; &gt;
        ///&lt;span class=&quot;article&quot;&gt;&lt;/span&gt;
        ///&lt;a href=&quot;/Page1/SubPage1/&quot; class=&quot;toc-entry&quot;&gt;sp1&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;li&gt;
        ///&lt;div class=&quot;tree-toc-node pointer&quot; &gt;
        ///&lt;span class=&quot;article&quot;&gt;&lt;/span&gt;
        ///&lt;a href=&quot;/Page1/SubPage2/&quot; class=&quot;toc-entry&quot;&gt;sp2&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string toc5 {
            get {
                return ResourceManager.GetString("toc5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;div id=&quot;toc&quot;&gt;
        ///&lt;a href=&quot;/&quot; class=&quot;toc-entry  active&quot;&gt;custom-title&lt;/a&gt;
        ///&lt;ul style=&quot;margin: 0px&quot; class=&quot;toc-container collapse in&quot;&gt;
        ///&lt;/ul&gt;
        ///&lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string toc6 {
            get {
                return ResourceManager.GetString("toc6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;div id=&quot;toc&quot;&gt;
        ///&lt;a href=&quot;/&quot; class=&quot;toc-entry  active&quot;&gt;Welcome&lt;/a&gt;
        ///&lt;ul style=&quot;margin: 0px&quot; class=&quot;toc-container collapse in&quot;&gt;
        ///&lt;li&gt;
        ///&lt;div class=&quot;tree-toc-node pointer&quot; &gt;
        ///&lt;span class=&quot;article&quot;&gt;&lt;/span&gt;
        ///&lt;a href=&quot;/SubPage2/&quot; class=&quot;toc-entry&quot;&gt;sp2&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;li&gt;
        ///&lt;div class=&quot;tree-toc-node pointer&quot; &gt;
        ///&lt;span class=&quot;article&quot;&gt;&lt;/span&gt;
        ///&lt;a href=&quot;/SubPage1/&quot; class=&quot;toc-entry&quot;&gt;sp1&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string toc7 {
            get {
                return ResourceManager.GetString("toc7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;div id=&quot;toc&quot;&gt;
        ///&lt;a href=&quot;/&quot; class=&quot;toc-entry  active&quot;&gt;Welcome&lt;/a&gt;
        ///&lt;ul style=&quot;margin: 0px&quot; class=&quot;toc-container collapse in&quot;&gt;
        ///&lt;li&gt;
        ///&lt;div class=&quot;tree-toc-node pointer&quot; &gt;
        ///&lt;span class=&quot;article&quot;&gt;&lt;/span&gt;
        ///&lt;a href=&quot;/SubPage2/&quot; class=&quot;toc-entry&quot;&gt;sp2&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string toc8 {
            get {
                return ResourceManager.GetString("toc8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string toc9 {
            get {
                return ResourceManager.GetString("toc9", resourceCulture);
            }
        }
    }
}
