//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Header1
        ///## Header2
        ///
        ///[link](https://www.google.com)
        ///
        ///*italic* text and **bold** text
        ///
        ///~~~cs
        ///var a = new Class1();
        ///a.DoWork(&quot;Hello World&quot;);
        ///~~~
        ///
        ///&lt;div&gt;
        ///&lt;b&gt;Some text&lt;/b&gt; inside div
        ///&lt;/div&gt;
        ///
        ///&gt; Quote
        ///
        ///&lt;div&gt;
        ///    @foreach (var item in Model.Pages) {    
        ///        &lt;a href=&quot;@item.Url&quot;&gt;@item.Label&lt;/a&gt;
        ///    }
        ///&lt;/div&gt;
        ///
        ///More text
        ///
        ///* Item 1
        ///* Item 2
        ///	* Sub Item1
        ///	* Sub Item2
        ///		* Sub Sub Item1
        ///* Item 3
        ///
        ///1. ListItem1
        ///1. ListItem2
        ///	1. SubListItem1
        ///1. ListItem3.
        /// </summary>
        internal static string Sample1 {
            get {
                return ResourceManager.GetString("Sample1", resourceCulture);
            }
        }
    }
}
