//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Components.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Components.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script async src=&quot;https://www.googletagmanager.com/gtag/js?id=ABC&quot;&gt;&lt;/script&gt;
        ///&lt;script&gt;
        ///window.dataLayer = window.dataLayer || [];
        ///function gtag() { dataLayer.push(arguments); }
        ///gtag(&apos;js&apos;, new Date());
        ///gtag(&apos;config&apos;, ABC);
        ///&lt;/script&gt;.
        /// </summary>
        internal static string google_analytics1 {
            get {
                return ResourceManager.GetString("google-analytics1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;ul class=&quot;menu sub-menu-item-container&quot; id=&quot;top-menu&quot;&gt;
        ///&lt;a class=&quot;menu-icon&quot; onclick=&quot;OpenMenu(this)&quot;&gt;
        ///&lt;div class=&quot;bar1&quot;&gt;&lt;/div&gt;
        ///&lt;div class=&quot;bar2&quot;&gt;&lt;/div&gt;
        ///&lt;div class=&quot;bar3&quot;&gt;&lt;/div&gt;
        ///&lt;/a&gt;
        ///&lt;li class=&quot;menu-item&quot;&gt;
        ///&lt;a href=&quot;&quot;&gt;Page1&lt;/a&gt;
        ///&lt;ul class=&quot;sub-menu-item-container&quot;&gt;
        ///&lt;li class=&quot;menu-item&quot;&gt;
        ///&lt;a href=&quot;/p2.html&quot;&gt;p2&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;li class=&quot;menu-item&quot;&gt;
        ///&lt;a href=&quot;&quot;&gt;SubPage2&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;/li&gt;
        ///&lt;li class=&quot;menu-item&quot;&gt;
        ///&lt;a href=&quot;&quot;&gt;Page2&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string nav1 {
            get {
                return ResourceManager.GetString("nav1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;ul class=&quot;menu sub-menu-item-container&quot; id=&quot;top-menu&quot;&gt;
        ///&lt;a class=&quot;menu-icon&quot; onclick=&quot;OpenMenu(this)&quot;&gt;
        ///&lt;div class=&quot;bar1&quot;&gt;&lt;/div&gt;
        ///&lt;div class=&quot;bar2&quot;&gt;&lt;/div&gt;
        ///&lt;div class=&quot;bar3&quot;&gt;&lt;/div&gt;
        ///&lt;/a&gt;
        ///&lt;li class=&quot;menu-item&quot;&gt;
        ///&lt;a href=&quot;/Page1.html&quot;&gt;p1&lt;/a&gt;
        ///&lt;ul class=&quot;sub-menu-item-container&quot;&gt;
        ///&lt;li class=&quot;menu-item&quot;&gt;
        ///&lt;a href=&quot;/SubPage1.html&quot;&gt;sp1&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;li class=&quot;menu-item&quot;&gt;
        ///&lt;a href=&quot;/SubPage2.html&quot;&gt;sp2&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;/li&gt;
        ///&lt;li class=&quot;menu-item&quot;&gt;
        ///&lt;a href=&quot;/Page2.html&quot;&gt;p2&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string nav2 {
            get {
                return ResourceManager.GetString("nav2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;ul class=&quot;menu sub-menu-item-container&quot; id=&quot;top-menu&quot;&gt;
        ///&lt;a class=&quot;menu-icon&quot; onclick=&quot;OpenMenu(this)&quot;&gt;
        ///&lt;div class=&quot;bar1&quot;&gt;&lt;/div&gt;
        ///&lt;div class=&quot;bar2&quot;&gt;&lt;/div&gt;
        ///&lt;div class=&quot;bar3&quot;&gt;&lt;/div&gt;
        ///&lt;/a&gt;
        ///&lt;li class=&quot;menu-item active&quot;&gt;
        ///&lt;a href=&quot;/&quot;&gt;Home&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;li class=&quot;menu-item&quot;&gt;
        ///&lt;a href=&quot;/Page1.html&quot;&gt;p1&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string nav3 {
            get {
                return ResourceManager.GetString("nav3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;ul class=&quot;menu sub-menu-item-container&quot; id=&quot;top-menu&quot;&gt;
        ///&lt;a class=&quot;menu-icon&quot; onclick=&quot;OpenMenu(this)&quot;&gt;
        ///&lt;div class=&quot;bar1&quot;&gt;&lt;/div&gt;
        ///&lt;div class=&quot;bar2&quot;&gt;&lt;/div&gt;
        ///&lt;div class=&quot;bar3&quot;&gt;&lt;/div&gt;
        ///&lt;/a&gt;
        ///&lt;li class=&quot;menu-item&quot;&gt;
        ///&lt;a href=&quot;/Page1.html&quot;&gt;x1&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string nav4 {
            get {
                return ResourceManager.GetString("nav4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;ul class=&quot;menu sub-menu-item-container&quot; id=&quot;top-menu&quot;&gt;
        ///&lt;a class=&quot;menu-icon&quot; onclick=&quot;OpenMenu(this)&quot;&gt;
        ///&lt;div class=&quot;bar1&quot;&gt;&lt;/div&gt;
        ///&lt;div class=&quot;bar2&quot;&gt;&lt;/div&gt;
        ///&lt;div class=&quot;bar3&quot;&gt;&lt;/div&gt;
        ///&lt;/a&gt;
        ///&lt;li class=&quot;menu-item&quot;&gt;
        ///&lt;a href=&quot;/SubPage1.html&quot;&gt;sp1&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;li class=&quot;menu-item&quot;&gt;
        ///&lt;a href=&quot;/SubPage2.html&quot;&gt;sp2&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string nav5 {
            get {
                return ResourceManager.GetString("nav5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;meta name=&quot;generator&quot; content=&quot;Docify&quot; /&gt;
        ///&lt;meta name=&quot;description&quot; content=&quot;d1&quot; /&gt;
        ///&lt;link rel=&quot;canonical&quot; href=&quot;www.example.com&quot; /&gt;
        ///&lt;meta property=&quot;og:title&quot; content=&quot;p1&quot; /&gt;
        ///&lt;meta property=&quot;og:locale&quot; /&gt;
        ///&lt;meta property=&quot;og:description&quot; content=&quot;d1&quot; /&gt;
        ///&lt;meta property=&quot;og:url&quot; content=&quot;www.example.com&quot; /&gt;
        ///&lt;meta property=&quot;og:site_name&quot; content=&quot;t1&quot; /&gt;
        ///&lt;meta property=&quot;og:image&quot; /&gt;
        ///&lt;meta name=&quot;twitter:card&quot; content=&quot;d1&quot; /&gt;
        ///&lt;meta name=&quot;twitter:site&quot; content=&quot;www.example.com&quot; /&gt;
        ///&lt;meta name=&quot;twitter:titl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string seo1 {
            get {
                return ResourceManager.GetString("seo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;meta name=&quot;generator&quot; content=&quot;Docify&quot; /&gt;
        ///&lt;meta name=&quot;description&quot; content=&quot;d1&quot; /&gt;
        ///&lt;link rel=&quot;canonical&quot; href=&quot;www.example.com&quot; /&gt;
        ///&lt;meta property=&quot;og:title&quot; content=&quot;p1&quot; /&gt;
        ///&lt;meta property=&quot;og:locale&quot; /&gt;
        ///&lt;meta property=&quot;og:description&quot; content=&quot;d1&quot; /&gt;
        ///&lt;meta property=&quot;og:url&quot; content=&quot;www.example.com&quot; /&gt;
        ///&lt;meta property=&quot;og:site_name&quot; content=&quot;t1&quot; /&gt;
        ///&lt;meta property=&quot;og:image&quot; /&gt;.
        /// </summary>
        internal static string seo2 {
            get {
                return ResourceManager.GetString("seo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;meta name=&quot;generator&quot; content=&quot;Docify&quot; /&gt;
        ///&lt;meta name=&quot;description&quot; content=&quot;d1&quot; /&gt;
        ///&lt;link rel=&quot;canonical&quot; href=&quot;www.example.com&quot; /&gt;
        ///&lt;meta name=&quot;twitter:card&quot; content=&quot;d1&quot; /&gt;
        ///&lt;meta name=&quot;twitter:site&quot; content=&quot;www.example.com&quot; /&gt;
        ///&lt;meta name=&quot;twitter:title&quot; content=&quot;p1&quot; /&gt;
        ///&lt;meta name=&quot;twitter:description&quot; content=&quot;d1&quot; /&gt;
        ///&lt;meta name=&quot;twitter:image&quot; /&gt;.
        /// </summary>
        internal static string seo3 {
            get {
                return ResourceManager.GetString("seo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;meta name=&quot;generator&quot; content=&quot;Docify&quot; /&gt;
        ///&lt;meta name=&quot;description&quot; content=&quot;d1&quot; /&gt;
        ///&lt;link rel=&quot;canonical&quot; href=&quot;www.example.com&quot; /&gt;
        ///&lt;script type=&quot;application/ld+json&quot;&gt;
        ///{&quot;url&quot;:&quot;www.example.com&quot;,&quot;description&quot;:&quot;d1&quot;,&quot;headline&quot;:&quot;sd1&quot;,&quot;image&quot;:null,&quot;@type&quot;:&quot;WebPage&quot;,&quot;@context&quot;:&quot;http://schema.org&quot;}
        ///&lt;/script&gt;.
        /// </summary>
        internal static string seo4 {
            get {
                return ResourceManager.GetString("seo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;div id=&quot;toc&quot;&gt;
        ///&lt;ul style=&quot;margin: 0px&quot; class=&quot;toc-container collapse in&quot;&gt;
        ///&lt;li&gt;
        ///&lt;div class=&quot;tree-toc-node pointer&quot; onclick=&quot;javascript:toggle(n1Span, n1);&quot;&gt;
        ///&lt;span class=&quot;expbutton&quot; id=&quot;n1Span&quot;&gt;&amp;#9656;&lt;/span&gt;
        ///&lt;span class=&quot;section&quot;&gt;&lt;/span&gt;
        ///&lt;a href=&quot;&quot; class=&quot;toc-entry&quot;&gt;Page1&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;ul id=&quot;n1&quot; class=&quot;toc-container collapse &quot;&gt;
        ///&lt;li&gt;
        ///&lt;div class=&quot;tree-toc-node pointer&quot; &gt;
        ///&lt;span class=&quot;article&quot;&gt;&lt;/span&gt;
        ///&lt;a href=&quot;/p2.html&quot; class=&quot;toc-entry&quot;&gt;p2&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;li&gt;
        ///&lt;div class=&quot;tree-toc-node pointer&quot; &gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string toc1 {
            get {
                return ResourceManager.GetString("toc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;div id=&quot;toc&quot;&gt;
        ///&lt;ul style=&quot;margin: 0px&quot; class=&quot;toc-container collapse in&quot;&gt;
        ///&lt;li&gt;
        ///&lt;div class=&quot;tree-toc-node pointer&quot; onclick=&quot;javascript:toggle(n1Span, n1);&quot;&gt;
        ///&lt;span class=&quot;expbutton&quot; id=&quot;n1Span&quot;&gt;&amp;#9656;&lt;/span&gt;
        ///&lt;span class=&quot;section&quot;&gt;&lt;/span&gt;
        ///&lt;a href=&quot;/Page1.html&quot; class=&quot;toc-entry&quot;&gt;p1&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;ul id=&quot;n1&quot; class=&quot;toc-container collapse &quot;&gt;
        ///&lt;li&gt;
        ///&lt;div class=&quot;tree-toc-node pointer&quot; &gt;
        ///&lt;span class=&quot;article&quot;&gt;&lt;/span&gt;
        ///&lt;a href=&quot;/SubPage1.html&quot; class=&quot;toc-entry&quot;&gt;sp1&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;li&gt;
        ///&lt;div class=&quot;tree-toc- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string toc2 {
            get {
                return ResourceManager.GetString("toc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;div id=&quot;toc&quot;&gt;
        ///&lt;a href=&quot;/&quot; class=&quot;toc-entry  active&quot;&gt;Welcome&lt;/a&gt;
        ///&lt;ul style=&quot;margin: 0px&quot; class=&quot;toc-container collapse in&quot;&gt;
        ///&lt;li&gt;
        ///&lt;div class=&quot;tree-toc-node pointer&quot; &gt;
        ///&lt;span class=&quot;article&quot;&gt;&lt;/span&gt;
        ///&lt;a href=&quot;/Page1.html&quot; class=&quot;toc-entry&quot;&gt;p1&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string toc3 {
            get {
                return ResourceManager.GetString("toc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;div id=&quot;toc&quot;&gt;
        ///&lt;ul style=&quot;margin: 0px&quot; class=&quot;toc-container collapse in&quot;&gt;
        ///&lt;li&gt;
        ///&lt;div class=&quot;tree-toc-node pointer&quot; &gt;
        ///&lt;span class=&quot;article&quot;&gt;&lt;/span&gt;
        ///&lt;a href=&quot;/Page1.html&quot; class=&quot;toc-entry&quot;&gt;x1&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string toc4 {
            get {
                return ResourceManager.GetString("toc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;div id=&quot;toc&quot;&gt;
        ///&lt;ul style=&quot;margin: 0px&quot; class=&quot;toc-container collapse in&quot;&gt;
        ///&lt;li&gt;
        ///&lt;div class=&quot;tree-toc-node pointer&quot; &gt;
        ///&lt;span class=&quot;article&quot;&gt;&lt;/span&gt;
        ///&lt;a href=&quot;/SubPage1.html&quot; class=&quot;toc-entry&quot;&gt;sp1&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;li&gt;
        ///&lt;div class=&quot;tree-toc-node pointer&quot; &gt;
        ///&lt;span class=&quot;article&quot;&gt;&lt;/span&gt;
        ///&lt;a href=&quot;/SubPage2.html&quot; class=&quot;toc-entry&quot;&gt;sp2&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string toc5 {
            get {
                return ResourceManager.GetString("toc5", resourceCulture);
            }
        }
    }
}
