//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fragments.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fragments.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;meta name=&quot;generator&quot; content=&quot;Docify v0.1&quot; /&gt;
        ///&lt;meta name=&quot;description&quot; /&gt;
        ///&lt;link rel=&quot;canonical&quot; href=&quot;www.example.com/p2/index.html&quot; /&gt;
        ///&lt;meta property=&quot;og:title&quot; content=&quot;p2&quot; /&gt;
        ///&lt;meta property=&quot;og:locale&quot; /&gt;
        ///&lt;meta property=&quot;og:description&quot; /&gt;
        ///&lt;meta property=&quot;og:url&quot; content=&quot;www.example.com/p2/index.html&quot; /&gt;
        ///&lt;meta property=&quot;og:site_name&quot; content=&quot;t1&quot; /&gt;
        ///&lt;meta property=&quot;og:image&quot; /&gt;
        ///&lt;meta name=&quot;twitter:card&quot; /&gt;
        ///&lt;meta name=&quot;twitter:site&quot; content=&quot;www.example.com/p2/index.html&quot; /&gt;
        ///&lt;meta name=&quot;twit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string seo1 {
            get {
                return ResourceManager.GetString("seo1", resourceCulture);
            }
        }
    }
}
