//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xarial.Docify.Lib.Plugins.TipueSearch.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xarial.Docify.Lib.Plugins.TipueSearch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;link href=&quot;/assets/tipuesearch/normalize.min.css&quot;&gt;
        ///&lt;script src=&quot;/assets/tipuesearch/jquery.min.js&quot;&gt;&lt;/script&gt;
        ///
        ///&lt;script src=&quot;search-content.js&quot;&gt;&lt;/script&gt;
        ///&lt;link rel=&quot;stylesheet&quot; href=&quot;/assets/styles/tipue-search.css&quot;&gt;
        ///&lt;script src=&quot;/assets/tipuesearch/tipuesearch_set.js&quot;&gt;&lt;/script&gt;
        ///&lt;script src=&quot;/assets/tipuesearch/tipuesearch.min.js&quot;&gt;&lt;/script&gt;
        ///
        ///&lt;div id=&quot;tipue_search_content&quot;&gt;&lt;/div&gt;
        ///&lt;script&gt;
        ///    $(document).ready(function () {
        ///        $(&apos;#tipue_search_input&apos;).tipuesearch();
        ///    });
        ///&lt;/script&gt;.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tipue_search {
            get {
                object obj = ResourceManager.GetObject("tipue_search", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;form action=&quot;/search/&quot;&gt;
        ///    &lt;div class=&quot;tipue_search_group&quot;&gt;
        ///        &lt;input type=&quot;image&quot; src=&quot;/assets/images/search.svg&quot; class=&quot;tipue_search_button&quot; width=&quot;25px&quot; border=&quot;0&quot; alt=&quot;Submit&quot; /&gt;
        ///        &lt;div style=&quot;overflow: hidden;padding-right: .5em;&quot;&gt;
        ///            &lt;input type=&quot;text&quot; name=&quot;q&quot; id=&quot;tipue_search_input&quot; placeholder=&quot;Search&quot; pattern=&quot;.{3,}&quot; title=&quot;At least 3 characters&quot; required&gt;
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///&lt;/form&gt;.
        /// </summary>
        internal static string tipue_search_box {
            get {
                return ResourceManager.GetString("tipue_search_box", resourceCulture);
            }
        }
    }
}
